tasks:
  - name: Setup .env
    init: cp .env.example .env

  - name: Get Laravel Sail dependencies via docker
    init: |
      docker run --rm \-u "$(id -u):$(id -g)" \-v "$(pwd):/app" -w /app \composer:2 \composer install --ignore-platform-reqs
      gp sync-done composer

  - name: Execute Laravel Sail
    init: gp sync-await composer
    command: ./vendor/bin/sail up
  
  - name: Run dev
    before: ./vendor/bin/sail bash
    init: php artisan key:generate && php artisan storage:link
    command: composer install && npm install && npm run dev
