tasks:
  - name: Setup .env
    init: cp .env.example .env

  - name: Get Laravel Sail dependencies via docker
    init: docker run --rm \-u "$(id -u):$(id -g)" \-v "$(pwd):/app" -w /app \composer:2 \composer install --ignore-platform-reqs
    command: ./vendor/bin/sail up
  
  - name: Run dev
    before: ./vendor/bin/sail bash
    init: | 
      gp sync-await composer
      php artisan key:generate && php artisan storage:link
    command: composer install && npm install && npm run dev

  #- name: Generate Laravel app key and storage symlink
  #  init: ./vendor/bin/sail bash
  #  command: php artisan key:generate && php artisan storage:link


