tasks:
  - name: Get Composer dependencies for the first time (we don't have Sail dependencies at this moment, so we use Composer Docker image)
    # Fix because of https://github.com/gitpod-io/gitpod/issues/16614
    before: |
      sudo curl -o /usr/local/bin/docker-compose -fsSL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-$(uname -m)
      echo "alias dc=docker-compose" >> ~/.bash_aliases
    init: |
      docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/app" -w /app composer:2 composer install --ignore-platform-reqs
      gp sync-done composer-dependencies

  - name: Setup Sail environment
    init: |
      cp .env.example .env
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8080)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5174)#g" .env

  - name: Execute Laravel Sail
    command: >
      gp sync-await composer-dependencies &&
      docker-compose up -d &&
      docker-compose exec webapp bash -c "php artisan key:generate && php artisan storage:link" &&
      gp sync-done sail-up

  - name: Get composer deps
    command: >
      gp sync-await sail-up &&
      docker-compose exec webapp bash -c "npm install && npm run dev"

ports:
  - port: 5174
    onOpen: ignore
    visibility: public
    name: Vite Server

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ikappas.composer
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - wmaurer.change-case
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
    - rangav.vscode-thunder-client
