tasks:
  - init: >
      touch database/database.sqlite &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate --seed
    command: >
      php artisan serve --host=0.0.0.0
    openMode: split-right
    name: WebServer
  - init: >
      npm i
    command: >
      npm run dev
    openMode: split-right
    name: npmDev
ports:
  - name: Laravel
    port: 8000
    visibility: private
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Vite
