tasks:
  - name: Setup .env
    init: cp .env.example .env

  - name: Get Laravel Sail dependencies via docker
    #init does not terminate
    init: docker run --rm \-u "$(id -u):$(id -g)" \-v "$(pwd):/app" -w /app \composer:2 \composer install --ignore-platform-reqs

  - name: Execute Laravel Sail
    before: gp sync-await docker
    command: ./vendor/bin/sail up
  
  - name: Run dev
    before: |
     gp sync-await docker
     ./vendor/bin/sail bash
    init: php artisan key:generate && php artisan storage:link
    command: composer install && npm install && npm run dev

  #- name: Generate Laravel app key and storage symlink
  #  init: ./vendor/bin/sail bash
  #  command: php artisan key:generate && php artisan storage:link


